  version: '3'
  services:
    database:
      image: postgres:12    
      restart: always
      # Use to Define network mode for the container
      network_mode: "host"
      volumes:
        - pgdata:/var/lib/postgresql/data
        - pgconf:/etc/postgresql
        - pglog:/var/log/postgresql
      environment:
        - POSTGRES_USER=$(POSTGRES_USER)
        - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
        - POSTGRES_DB=$(POSTGRES_DB)
        - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
        - pgdata:/var/lib/postgresql/data
        
    backend:
      image : backend 
      network_mode: "host"
      depends_on:
        - database
      environment:
        - DB_HOST=$(DB_HOST)
        - DB_USER=$(DB_USER)
        - DB_PASS=$(DB_PASS)
        - DB_NAME=$(DB_NAME)

    frontend:
      image: frontend
      network_mode: "host"
        # First one is the host port and second one is the container port
      depends_on:
        - backend
      environment:
        - POST_API_URL=$(POST_API_URL)
        - GET_API_URL=$(GET_API_URL)

  # volumes for PostgreSQL data, configuration, and logs.
  volumes:
      pgdata:
        driver: local
      pgconf:
        driver: local
      pglog: 
        driver: local