  version: '3'
  services:
    database:
      image: postgres:12    
      restart: always
      # Use to Define network mode for the container
      network_mode: "host"
      volumes:
        - pgdata:/var/lib/postgresql/data
        - pgconf:/etc/postgresql
        - pglog:/var/log/postgresql
      environment:
        - POSTGRES_USER='postgres'
        - POSTGRES_PASSWORD='Priyanshu12!'
        - POSTGRES_DB='postgres'
        - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
        
    backend:
      image : backend
      network_mode: "host"
      depends_on:
        - database
      environment:
        - DB_HOST='database'
        - DB_USER='postgres'
        - DB_PASS='Priyanshu12!'
        - DB_NAME='postgres'

    frontend:
      image: frontend
      network_mode: "host"
      depends_on:
        - backend
      environment:
        - POST_API_URL='http://localhost:8080/postData'
        - GET_API_URL='http://localhost:8080/getData'

  # volumes for PostgreSQL data, configuration, and logs.
  volumes:
      pgdata:
        driver: local
      pgconf:
        driver: local
      pglog: 
        driver: local